server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/elk_db?useSSL=false
    username: root
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.newhand.hotel.pojo