server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: cloud
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  # 增加nacos配置
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ # 集群名称
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    top.newhand: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS